# Generated by Django 5.1 on 2025-02-08 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('profile_picture', models.ImageField(blank=True, default='userprofile/userprofile.jpg', null=True, upload_to='userprofile', verbose_name='Profile Picture')),
                ('country', models.CharField(blank=True, default='India', max_length=50, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='District')),
                ('postal_code', models.CharField(blank=True, max_length=50, verbose_name='Postal Code')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserImportantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('crop_grown', models.CharField(blank=True, max_length=50, verbose_name='Crop Grown')),
                ('land_area', models.FloatField(blank=True, default=0, null=True, verbose_name='Land Area')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='Planting Date')),
                ('receive_email', models.BooleanField(default=True, verbose_name='Receive Email')),
                ('receive_push_notification', models.BooleanField(default=False, verbose_name='Receive Email')),
                ('receive_sms', models.BooleanField(default=False, verbose_name='Receive SMS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='important_details', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Important Detail',
                'verbose_name_plural': 'User Important Details',
            },
        ),
    ]
